stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    # Ersetze <your_docker_image_for_bot> durch den tatsächlichen Namen
    - docker build -t ai_support_bot ./bot
    - docker build -t ai_analysis_service ./ai_analysis
    - docker build -t security_check_service ./security_check
    - docker-compose up -d
  only:
    - master

test:
  stage: test
  script:
    - pytest tests/

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/
    - kubectl rollout restart deployment ai-support-bot
  only:
    - master
