apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-support-bot
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/DEIN_USERNAME/AI_Support_Bot
    targetRevision: master
    path: k8s
  project: default
