services:
  ai_analysis:
    build:
      context: .
      dockerfile: app/ai_analysis/Dockerfile

  bot:
    build:
      context: .
      dockerfile: app/bot/Dockerfile

  security_check:
    build:
      context: .
      dockerfile: app/security_check/Dockerfile
