version: '3'
services:
  bot:
    build: ./docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=your_openai_api_key
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: logs_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
