services:
  bot:
    build:
      context: .
      dockerfile: app/bot/Dockerfile
    image: ai-support-bot-bot
    volumes:
      - ./shared:/app/shared
    env_file:
      - app/bot/.env

  app:
    build:
      context: .
      dockerfile: app/UI/Dockerfile
    image: ai-support-bot-bot-2
    volumes:
      - ./shared:/app/shared
    env_file:
      - app/bot/.env
    ports:
      - "7860:7860"

  ai_analysis:
    build:
      context: .
      dockerfile: app/ai_analysis/Dockerfile
    volumes:
      - ./shared:/app/shared
    env_file:
      - app/bot/.env

  security_check:
    build:
      context: .
      dockerfile: app/security_check/Dockerfile
    image: ai-support-bot-security-check
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared:/app/shared
    environment:
      TRIVY_IMAGE: ai-support-bot-bot
      CHECK_INTERVAL: 120
      TRIVY_TIMEOUT: 600
      TRIVY_REPORT_PATH: /app/shared/trivy_output.json
    env_file:
      - app/bot/.env


