
services:
  ai_analysis:
    build:
      context: .
      dockerfile: ai_analysis/Dockerfile
    volumes:
      - ./requirements.txt:/app/requirements.txt
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - ./requirements.txt:/app/requirements.txt
  security_check:
    build:
      context: .
      dockerfile: security_check/Dockerfile
    volumes:
      - ./requirements.txt:/app/requirements.txt
