version: '3'
services:
  bot:
    build: ./bot
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=your_openai_api_key
    depends_on:
      - db

  ai_analysis:
    build: ./ai_analysis
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=your_openai_api_key
    depends_on:
      - db

  security_check:
    build: ./security_check
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: logs_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
