apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-analysis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-analysis
  template:
    metadata:
      labels:
        app: ai-analysis
    spec:
      containers:
        - name: ai-analysis-service
          image: ai-support-bot-ai_analysis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: OPENAI_API_KEY
              value: "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"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-analysis-service
spec:
  selector:
    app: ai-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP