apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot-service
          image: ai-support-bot-bot:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DISCORD_WEBHOOK_URL
              value: "https://discord.com/api/webhooks/..."
            - name: MODEL_HUMOR_PATH
              value: "/app/shared/model_humor.txt"
            - name: TRIVY_REPORT_PATH
              value: "/app/shared/trivy_output.json"
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
