apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot-service
          image: <your_docker_image_for_bot>
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
