apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-support-bot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-support-bot
  template:
    metadata:
      labels:
        app: ai-support-bot
    spec:
      containers:
        - name: ai-support-bot
          image: docker.io/library/ai-support-bot-app:latest
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "while true; do sleep 3600; done" ]
