name: Docker Image Scan

on: [push]

env:
  USER: "esraakrayym"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
            
            
            
            
      - name: Build Docker images
        run: |
          docker build -t ai_support_bot -f app/bot/Dockerfile .
          docker build -t ai_analysis_service -f app/ai_analysis/Dockerfile .
          docker build -t security_check_service -f app/security_check/Dockerfile .
      
      

     

      # Install Trivy (Specific version v0.60.1)
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: latest # Specify the desired version

      # Build the new Docker image with trivy_output.json
      - name: Build the new Docker image with trivy_output.json
        run: |
          docker build -t ghcr.io/$USER/ai-support-bot-with-trivy-output:latest -f Dockerfile.trivy-analysis .


      - name: Push ai_support_bot to GHCR
        run: |
          docker tag ai_support_bot ghcr.io/${{ github.actor }}/ai_support_bot:latest
          docker push ghcr.io/${{ github.actor }}/ai_support_bot:latest
          
          # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/$USER/ai-support-bot-with-trivy-output:latest
